#run with sudo docker-compose up
---
version: "2.1"
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PUBLIC_KEY=key.pub #optional
      - PUBLIC_KEY_FILE=key.priv #optional
   #   - PUBLIC_KEY_DIR=/ #optional
    #  - PUBLIC_KEY_URL=https://github.com/username.keys #optional
    #  - SUDO_ACCESS=true #optional
     # - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
 #     - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=test #optional
#      - /path/to/appdata/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped
